### ISSUE TITLE
Add `languages.tsv`

### ISSUE THREAD

**Issue by moritz-topp** [digling/gaotb#1]
`etc/languages.tsv` should show:

- [x] names of the language varieties
- [x] the geocoordinates (`Longitude` and `Latitude`)
- [x] the identifiers (alphanumeric representations)

**Comment by MuffinLinwist** [comment]
There are three languages on the dataset, namely `MojiangYi`, `LijangNaxi`, and `YongningNaxi`, for which the resulting Family entry on the `cldf/languages.csv` file signals `Bookkeeping`. Fixing this is a goal to close: [https://github.com/lexibank/lexibank-analysed/issues/46](https://github.com/lexibank/lexibank-analysed/issues/46)

**Comment by MuffinLinwist** [comment]
Can I ask for permission to any of the contributors here to fix the problem, @LinguList? I believe I'll need to be granted permission to edit the repo.

**Comment by LinguList** [comment]
Granted :-)
